log-dir: G:\\log\\hrs-cloud\\

mainDomain: http://127.0.0.1:18182
miscDomain: http://127.0.0.1:18182
spring.datasource.type: com.zaxxer.hikari.HikariDataSource
spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
spring.datasource.url: jdbc:mysql://192.168.118.132:3306/hrs?useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username: root
spring.datasource.password: 1
spring.datasource.hikari.maximum-pool-size: 500
spring.datasource.hikari.minimum-idle: 1
spring.datasource.hikari.idle-timeout: 60000
spring.datasource.hikari.connection-init-sql: set names utf8mb4;
mybatis.mapper-locations: classpath*:mapper/*.xml

jedis:
  pool:
    url: 127.0.0.1:6379
    config:
      maxTotal: 1000
      minIdle: 5
      maxIdle: 100
      testOnBorrow: false
      maxWaitMillis: 5000
      testOnReturn: true
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 10000

spring.freemarker.template-loader-path: classpath:/templates/
spring.freemarker.cache: false
spring.freemarker.charset: UTF-8
spring.freemarker.check-template-location: true
spring.freemarker.content-type: text/html
spring.freemarker.expose-request-attributes: true
spring.freemarker.expose-session-attributes: true
spring.freemarker.request-context-attribute: request
spring.freemarker.suffix: .ftl
spring.freemarker.settings.number_format: 0.####

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB # 单个文件的最大值
      max-request-size: 100MB # 上传文件总的最大值

tempPdfPath: G://log//hrs-cloud//temp/
picUpload: G://log//hrs-cloud//upload/
picDomain: http://127.0.0.1/
virtulPath: /pic/
pdfvirtulPath: /pdf/


task:
  ip: 127.0.0.1

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/hrs/cloud/**/mapper/*.xml
  typeAliasesPackage: com.hrs.cloud.**.entity
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true #开启驼峰功能
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用=======