package com.hrs.cloud.entity;

public class Tickets64 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickets64.id
     *
     * @mbggenerated Tue Mar 27 23:11:32 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickets64.stub
     *
     * @mbggenerated Tue Mar 27 23:11:32 CST 2018
     */
    private String stub;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickets64.id
     *
     * @return the value of tickets64.id
     *
     * @mbggenerated Tue Mar 27 23:11:32 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickets64.id
     *
     * @param id the value for tickets64.id
     *
     * @mbggenerated Tue Mar 27 23:11:32 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickets64.stub
     *
     * @return the value of tickets64.stub
     *
     * @mbggenerated Tue Mar 27 23:11:32 CST 2018
     */
    public String getStub() {
        return stub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickets64.stub
     *
     * @param stub the value for tickets64.stub
     *
     * @mbggenerated Tue Mar 27 23:11:32 CST 2018
     */
    public void setStub(String stub) {
        this.stub = stub == null ? null : stub.trim();
    }
}